// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXNzHrErEupeqWtAfAUcyvo66mx7jdrD8',
    appId: '1:708679598439:web:41c79aef437875a4a72fc2',
    messagingSenderId: '708679598439',
    projectId: 'melodify-music-app',
    authDomain: 'melodify-music-app.firebaseapp.com',
    storageBucket: 'melodify-music-app.appspot.com',
    measurementId: 'G-03K429CB80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7-YG10okb3TlocKC6wRX8JKZQ24k0sWI',
    appId: '1:708679598439:android:3d16db31fdb1aa05a72fc2',
    messagingSenderId: '708679598439',
    projectId: 'melodify-music-app',
    storageBucket: 'melodify-music-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOnprWZNqWpLuERN7wBQCXY0PrWxtFuRU',
    appId: '1:708679598439:ios:d31c9b4a42835cdba72fc2',
    messagingSenderId: '708679598439',
    projectId: 'melodify-music-app',
    storageBucket: 'melodify-music-app.appspot.com',
    iosBundleId: 'com.example.moodhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOnprWZNqWpLuERN7wBQCXY0PrWxtFuRU',
    appId: '1:708679598439:ios:d31c9b4a42835cdba72fc2',
    messagingSenderId: '708679598439',
    projectId: 'melodify-music-app',
    storageBucket: 'melodify-music-app.appspot.com',
    iosBundleId: 'com.example.moodhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXNzHrErEupeqWtAfAUcyvo66mx7jdrD8',
    appId: '1:708679598439:web:aff8749ce1a4404ba72fc2',
    messagingSenderId: '708679598439',
    projectId: 'melodify-music-app',
    authDomain: 'melodify-music-app.firebaseapp.com',
    storageBucket: 'melodify-music-app.appspot.com',
    measurementId: 'G-T7V5LV8FRW',
  );
}
